package com.hdsx.jhsjgx.api.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.HashMap;
import java.util.List;

/**
 * 处理导入广东和巴彦淖尔路况系统数据的sql语句
 * 
 * @author jkYishon
 *
 */
public interface DataReader {
    
    @Select("select BZ,SBTHCD,TZXZ,DC,SD,DQ,SDMC,KGSJ,WGSJ,GQ,SJDW,DQ_DK,QDZH,ZDZH,JSJSDJ,JSXZ,LJ,QL,HD,MC,JC,CBSJ_LMGZ,ID,XMMC,XMBM,JSDW,XZQH,SD_SFCD,SD_LX,SFBJ,MC_LC,JC_LC,DC_LC,DFZC,YHDK,SJPFWH,PFSJ,JAF,SHZT,SBZT,QL_YM,HD_M,SD_YM,DQ_CD,TZSJ,THYY,TZ,GYDWDM,XZQHDM,GYDW from CBSJ_LMGZ where xmbm in (select xmbm from lxsh_lmgz where gydwdm like #{value}) ")
    List<HashMap> selectCBSJ_LMGZ(String str);

    @Select("select CBSJ_SH,QDZH,ZDZH,JSJSDJ,JSXZ,KGSJ,WGSJ,GQ,SJDW,SJPFWH,ID,XMBM,XMMC,JSDW,XZQH,PFSJ,SHZT,SBZT,SFBJ,JSFA,MC,JC,DC,MC_LC,JC_LC,DC_LC,LC,TZXZ,TZSJ,SBTHCD,THYY,JAF,TZ,GYDWDM,XZQHDM,GYDW,BZ from CBSJ_SH where xmbm in (select xmbm from xmsq_SH where gydwdm like #{value})")
    List<HashMap> selectCBSJ_SH(String str);

    @Select("select BZ,LJ,QL,HD,MC,JC,DC,SD,DQ,SDMC,CBSJ_SJGZ,ID,XMMC,XMBM,JSDW,XZQH,QDZH,ZDZH,JSJSDJ,JSXZ,KGSJ,WGSJ,GQ,SJDW,SJPFWH,PFSJ,JAF,SFBJ,MC_LC,JC_LC,DC_LC,DFZC,YHDK,JSZLC,TZXZ,TZSJ,SHZT,SBZT,QL_YM,HD_M,SD_YM,DQ_CD,DQ_DK,SD_SFCD,SD_LX,GYDWDM,GYDW,XZQHDM,SBTHCD,THYY,TZ from CBSJ_SJGZ where xmbm in (select xmbm from lxsh_SJGZ where gydwdm like #{value}) ")
    List<HashMap> selectCBSJ_SJGZ(String str);

    @Select("select JSDW,SD_YM,DQ_CD,DQ_DK,SD_SFCD,SD_LX,SFBJ,MC_LC,JC_LC,DC_LC,MC,JC,DC,SD,DQ,SDMC,KGSJ,WGSJ,GQ,CBSJ_XJ,XZQH,QDZH,ZDZH,JSJSDJ,JSXZ,LJ,QL,HD,SJDW,SJPFWH,PFSJ,JAF,SHZT,SBZT,QL_YM,HD_M,DFZC,YHDK,TZXZ,TZSJ,SBTHCD,THYY,XZQHDM,GYDW,XMMC,ID,BZ,GYDWDM,TZ,XMBM from CBSJ_XJ where xmbm in (select xmbm from lxsh_XJ where gydwdm like #{value})")
    List<HashMap> selectCBSJ_XJ(String str);

    @Select("select BZ,SJDW,SJPFWH,PFSJ,SHZT,SBZT,JSFA,SFBJ,MC,JC,CBSJ_YHDZX,ID,XMBM,XMMC,JSDW,XZQH,QDZH,ZDZH,JSJSDJ,JSXZ,KGSJ,WGSJ,GQ,DC,MC_LC,JC_LC,DC_LC,LC,TZXZ,TZSJ,SBTHCD,TZ,GYDWDM,GYDW,THYY,XZQHDM,JAF from CBSJ_YHDZX where xmbm in (select xmbm from xmsq_YHDZX where gydwdm like #{value})")
    List<HashMap> selectCBSJ_YHDZX(String str);

    @Select("select ZGSHZT,ZGSHYJ,SFTH,WC_STZ,WC_QTTZ,BYZJSY,ZJDW_BTZ,ZJDW_STZ,ZJDW_QTTZ,SBYF,SBSJ,SBBM,GCGL_ABGC,WC_ZTZ,ID,JHID,BYWC_C,BYWC_GL,BYWCTZ,WC_BTZ,ISZH,ISZHQK,SHZT,SHUSER,SHTIME,KGDL,QKSM,ZJJE,XGCSYJ,SFSJ,WCQK,THYY,TBMAN,ZGSHTIME,ZGTHYY,ZGSHUSER from GCGL_ABGC ")
    List<HashMap> selectGCGL_ABGC(String str);

    @Select("select BCDWCD,ISSJ,YSSJ,NSQSJJLZJ,ID,JHID,YSDW,YSYJ,SFCCLQ from GCGL_JGYS")
    List<HashMap> selectGCGL_JGYS(String str);

    @Select("select WC_ZTZ,SHZT,SHUSER,SHTIME,BYWCMC,KGDL,QKSM,ZJJE,XGCSYJ,SFSJ,ISZHQK,GCGL_WQGZ,WC_BTZ,WC_STZ,WC_QTTZ,ZJDW_BTZ,ZJDW_STZ,ZJDW_QTTZ,WCQK,SBYF,SBSJ,SBBM,SFTH,ZJC,XBGZ,SBJG,ZGSHYJ,THYY,ZGTHYY,ZGSHUSER,ID,ISZH,ZGSHZT,ZGSHTIME,TBMAN,JHID from GCGL_WQGZ")
    List<HashMap> selectGCGL_WQGZ(String str);

    @Select("select WCSJBZZJ,XMBM,ZFCGS,ZFGZ,ZFSZ,ZFZQ,ZFDK,ZFJL,ZFQT,ZFDFZC,GCGL_XMJD,ISZH,ISZHQK,ID,ZFYHDK,ZFRYS,WCCGS,WCGZ,WCSZ,WCZQ,WCDK,LQ,SN,BNDSSLC,SSDCTC,WWCGCL,QKSM,TBR,TBSJ,YBYF,WCJL,WCQT,WCDFZC,WCYHDK,WCRYS,YILC,ERLC,SANLC,SILC,ZGSHYJ,ZGSHZT,SHYJ,SBZT,SHZT,THYY from GCGL_XMJD")
    List<HashMap> selectGCGL_XMJD(String str);

    @Select("select ZGSHZT,WC_BTZ,WC_STZ,WC_QTTZ,ZJDW_BTZ,ZJDW_STZ,ZJDW_QTTZ,BYWCGL,SHZT,SHUSER,ISZHQK,GCGL_ZHFZ,WC_ZTZ,ISZH,ID,JHID,SBYF,SBSJ,SBBM,SHTIME,KGDL,QKSM,ZJJE,XGCSYJ,SFSJ,SFTH,WCQK,ZGSHTIME,ZGSHUSER,ZGTHYY,ZGSHYJ,THYY,TBMAN from GCGL_ZHFZ")
    List<HashMap> selectGCGL_ZHFZ(String str);

    @Select("select THYY,JHSH_LMGZ,ID,XMBM,XDWH,XDSJ,PFZTZ,BBZZJ,SBZZJ,XMMC,XZQH,QDZH,ZDZH,KGSJ,WGSJ,SFGK,SJWGSJ,GZ,SZ,ZQ,DK,JL,QT,ZYDPX,GQ,GKPFWH,SJPFWH,XDZT,XJZT,SJZT,SJSH,KGZT,JGZT,SFQXKG,SGDW,JLDW,JSDW,SJKGSJ,YJWGSJ,HTJE,GYS,ZYJSNR,YHDK,DFZC,GLDJ,SBZT,XZSCNL from JHSH_LMGZ  where xmbm in (select xmbm from lxsh_lmgz where gydwdm like #{value})")
    List<HashMap> selectJHSH_LMGZ(String str);

    @Select("select THYY,ZYDPX,QT,DK,SZ,SJWGSJ,GYS,YJWGSJ,SJZT,SJSH,KGZT,JGZT,SFQXKG,SGDW,JLDW,JSDW,SJKGSJ,XDSJ,QDZH,ZDZH,LC,PFZTZ,BBZZJ,SBZZJ,XMMC,GHLXBH,JHSH_SH,DFZC,ID,XMBM,XDWH,YLXBH,GCFL,XZQH,JHKGSJ,JHWGSJ,XZQHDM,XDZT,XJZT,HTJE,SFGK,GZ,ZQ,JL,SBZT from JHSH_SH where xmbm in (select xmbm from xmsq_SH where gydwdm like #{value})")
    List<HashMap> selectJHSH_SH(String str);

    @Select("select THYY,GKPFWH,SJPFWH,XDZT,XJZT,SJZT,SJSH,KGZT,JGZT,SJWGSJ,BBZZJ,SBZZJ,XMMC,XZQH,QDZH,ZDZH,KGSJ,WGSJ,GQ,JHSH_SJGZ,ID,XMBM,XDWH,XDSJ,PFZTZ,JSZLC,GLDJ,GZ,SZ,ZQ,DK,JL,QT,SFQXKG,SGDW,JLDW,JSDW,SJKGSJ,YJWGSJ,HTJE,GYS,SFGK,ZYJSNR,YHDK,DFZC,ZYDPX,SBZT,XZSCNL from JHSH_SJGZ where xmbm in (select xmbm from lxsh_SJGZ where gydwdm like #{value})")
    List<HashMap> selectJHSH_SJGZ(String str);

    @Select("select THYY,JHSH_XJ,ID,XMBM,XDWH,XDSJ,SFQXKG,SGDW,JLDW,JSDW,SJKGSJ,YJWGSJ,HTJE,GYS,SFGK,GQ,GKPFWH,SJPFWH,XDZT,XJZT,SJZT,SJSH,KGZT,JGZT,PFZTZ,BBZZJ,SBZZJ,XMMC,XZQH,QDZH,ZDZH,KGSJ,WGSJ,SJWGSJ,GLDJ,GZ,SZ,ZQ,DK,JL,QT,ZYJSNR,YHDK,DFZC,ZYDPX,SBZT,XZSCNL from JHSH_XJ where xmbm in (select xmbm from lxsh_XJ where gydwdm like #{value})")
    List<HashMap> selectJHSH_XJ(String str);

    @Select("select XFCSL,RYS,DK,QT,SBZT,SFSYCGS,ZYDPX,JHXDWH_XD,THYY,ID,JCLX,XFCLX,MCLMLX,XJZT,SJZT,SJSH,KGZT,JGZT,SGDW,XMMC,GHLXBH,YLXBH,GCFL,XZQH,JHKGSJ,JHWGSJ,XZQHDM,XDZT,JHSH_YHDZX,XFCJE,BXSL,BXJE,GFCD,GFJE,LLCL,JLDW,JSDW,SJKGSJ,YJWGSJ,HTJE,GYS,SFGK,SJWGSJ,XMBM,XDWH,XDSJ,QDZH,ZDZH,LC,ZTZ,SYSBBZJ,JCSL,MCJE,MCSL,YQDBCGS,MCLX,JCJE from JHSH_YHDZX where xmbm in (select xmbm from xmsq_YHDZX where gydwdm like #{value})")
    List<HashMap> selectJHSH_YHDZX(String str);

    @Select("select BZ,TZSJ,YHDK,TBBMBM,DQ_M,KXXYJ_LMGZ,ID,XMMC,XMBM,JSXZ,GKPFWH,PFSJ,TZGS,BZDW,XZQHDM,SHZT,SBZT,SBTHCD,JSDW,XZQH,QDZH,ZDZH,DQ,SD,KGNY,WGNY,JSJSDJ,SD_M,DFZC,TZXZ,GYDW1,THYY,GYDWDM1 from KXXYJ_LMGZ  where xmbm in (select xmbm from lxsh_lmgz where gydwdm like #{value})")
    List<HashMap> selectKXXYJ_LMGZ(String str);

    @Select("select BZ,KGNY,WGNY,JSJSDJ,JSXZ,GKPFWH,PFSJ,TZGS,BZDW,XZQHDM,KXXYJ_SJGZ,ID,XMMC,XMBM,JSDW,XZQH,QDZH,ZDZH,DQ,SD,SHZT,SBZT,SBTHCD,DQ_M,SD_M,TBBMBM,DFZC,YHDK,GYDWDM1,GYDW1,TZSJ,JSZLC,TZXZ,THYY from KXXYJ_SJGZ where xmbm in (select xmbm from lxsh_SJGZ where gydwdm like #{value})")
    List<HashMap> selectKXXYJ_SJGZ(String str);

    @Select("select BZ,KXXYJ_XJ,ID,XMMC,XMBM,JSDW,XZQH,QDZH,ZDZH,BZDW,XZQHDM,SHZT,SBZT,SBTHCD,DQ_M,SD_M,TBBMBM,DFZC,DQ,SD,KGNY,WGNY,JSJSDJ,JSXZ,GKPFWH,PFSJ,TZGS,GYDWDM1,GYDW1,TZSJ,YHDK,TZXZ,THYY from KXXYJ_XJ where xmbm in (select xmbm from lxsh_XJ where gydwdm like #{value})")
    List<HashMap> selectKXXYJ_XJ(String str);

    @Select("select WJFILE,ID,TBDW,TBNF,BT4,BT3,BT2,BW,BT1,BT5 from LKPD_LKHZB")
    List<HashMap> selectLKPD_LKHZB(String str);

    @Select("select YLLV,ZDL,YDL,BCI,PQI,PDLC,ID,HZB_ID,LXBH,LXMC,QDZH,ZDZH,QJFX,MQI,SCI,TCI,LDL,CDL,CADL from LKPD_LKHZB_DATA")
    List<HashMap> selectLKPD_LKHZB_DATA(String str);

    @Select("select YZDZH,YLXBM,BZ,SRI,RQI,LDCD,TCI,SCI,ID,MXB_ID,LXBH,LXMC,QDZH,ZDZH,JCFX,JSDJ,MQI,PQI,BCI,LMLX,PCI,RDI,PSSI,YQDZH from LKPD_MXB_DATA_2014")
    List<HashMap> selectLKPD_MXB_DATA_2014(String str);

    @Select("select WJFILE,BT5,BT3,BT1,TBNF,ID,TBDW,BW,BT2,BT4 from LKPD_MXB2014")
    List<HashMap> selectLKPD_MXB2014(String str);

    @Select("select LXSH_LMGZ,XMKLX,WNID,XZQHDM2,BZ,LXMC,XJSDJ,XMBM,TZ,BZYS,DFZC,TSDQ,XZQH,GYDW,XZQHDM,ID,XMMC,GHLXBH,LC,JSXZ,QDZH,ZDZH,QDMC,ZDMC,JHKGN,JHWGN,JSJSDJ,GYDWDM,TBBMBM,TBBMMC,TBSJ,SHZT,SBZT,XMNF,SBTHCD,LSJL,YHDK,SFBFLX,THYY,LSXMBM,LSXMID from LXSH_LMGZ where gydwdm like #{value}")
    List<HashMap> selectLXSH_LMGZ(String str);

    @Select("select BC6HD,LXSH_LX,WBC,WBCHD,BC25HD,BC30HD,BMC25HD,WFCHD,XJFCHD,ID,XMID,LXBM,LXMC,XZQH,XZQHDM,GYDW,GYDWDM,QDZH,ZDZH,JSJSDJ,LC,XJSDJ,JSXZ,QDMC,ZDMC,BZCS,SFFIRST,JDBS,GPSQDZH,GPSZDZH,JSFA,YILC,ERLC,SANLC,SILC,DWLC,WLLC,JHYILC,JHERLC,JHSANLC,JHSILC,JHDWLC,JHWLLC,XJLXBM,XJQDZH,XJZDZH,XJLC,JHLC,GHLXBM,GHLXMC,LQHNTMCHD,LQHNTMC,GXLQHNTMCHD,GXLXBM,GXQDZH,GXZDZH,GHQDZH,GHZDZH,SNHNTMCHBMJ,ZXLWLXBM,ZXLWQDZH,ZXLWZDZH,SWJCLZS,XFCHD,XFC,WCSNMBHD,WCSNMB,WCSWJCHD,WCSWJC,SNHNTMCHBHD,SNHNTMCHB,LQLMPMLQJDLZSHD,LQLMPMLQJDLZS,LQLMRHLQJDLZSHD,LQLMRHLQJDLZS,LQLMCBLZSHD,LQLMCBLZS,XZRXJCHD,XZRXJC,SWJCLZSHD,GXLQHNTMC,SNHNTMCHD,SNHNTMC,LQLMJDRZSHD,LQLMJDRZS,LQLMCBRZSHD,LQLMCBRZS,SWJCHD,SWJC,BXHD,BX,SNHNTMCSSHHD,SNHNTMCSSH,SBZJ,LXLMKD,XZQHDM2,XZQHMC2,GHLXBMBF,GHQDZHBF,GHZDZHBF,XJLXBMBF,XJQDZHBF,XJZDZHBF,FCBC30,BC6,XJFC,WFC,BMC25,BC25,BC30,FCBC30HD from LXSH_LX ")
    List<HashMap> selectLXSH_LX(String str);

    @Select("select SHZT,XZQHDM2,SFBFLX,WNID,THYY,XMKLX,LSXMBM,LSXMID,ID,JHWGN,LXSH_SJGZ,SBZT,XMNF,SBTHCD,LXMC,LSJL,BZ,YHDK,JSZLC,JSJSDJ,XJSDJ,XMBM,TZ,BZYS,DFZC,TSDQ,XZQH,XMMC,GHLXBH,LC,JSXZ,QDZH,ZDZH,QDMC,ZDMC,JHKGN,TBBMMC,TBBMBM,GYDWDM,GYDW,XZQHDM,TBSJ from LXSH_SJGZ where gydwdm like #{value}")
    List<HashMap> selectLXSH_SJGZ(String str);

    @Select("select LSXMID,QDMC,ZDMC,JHKGN,JHWGN,JSJSDJ,XJSDJ,XMBM,TZ,TBSJ,LXSH_XJ,ID,XMMC,GHLXBH,LC,JSXZ,QDZH,ZDZH,SHZT,SBZT,XMNF,SBTHCD,LXMC,LSJL,BZ,YHDK,BZYS,DFZC,TSDQ,XZQH,GYDW,XZQHDM,GYDWDM,TBBMBM,TBBMMC,XMKLX,THYY,WNID,XZQHDM2,SFBFLX,LSXMBM from LXSH_XJ where gydwdm like #{value}")
    List<HashMap> selectLXSH_XJ(String str);

    @Select("select P.PLAN_AF,P.SPSJ,P.SPBM,P.SPZT,P.TBBM,P.TBSJ,P.ABLBZSQWH,P.SFSQABLBZ,P.JHSYDFZCZJ,P.JHSYBBZJE,P.SBZT,P.PFZTZ,P.PFSJ,P.PFWH,P.SJPFDW,P.SJDW,P.JHWGSJ,P.JHKGSJ,P.JHXDWH,P.JSDW,P.JHWC_C,P.YJWGSJ,P.JGZT,P.KGZT,P.WJSCZT,P.JGYSWJ,P.JGTCWJ,P.REMARKS,P.WJGYY,P.GYS,P.WJSJ,P.WJZT,P.XFBM,P.XFSJ,P.XFZT,P.XDZT,P.JHNF,P.SCKID,P.ID,P.TZSJ,P.TZXZ,P.JHYHLC,P.JHZLC,P.JHZDZH,P.JHQDZH,P.ZDYF,P.SJSH,P.SJZT,P.XJZT,P.SFYLSJL,P.SPBMDM,P.SBBMDM,P.JH_SBTHCD,P.SGXKWJ,P.HTJE,P.JLDW,P.SGDW,P.SJWGSJ,P.SJKGSJ,P.SJSGTLJ,P.SJSGTMC,P.SBBM,P.SBSJ,P.XDSJ,P.GKBGLJ,P.GKBGMC,P.SHENGBZ from PLAN_AF p,sck_aqsmfh s,sck_aqsmfh_ld sl,xmk_aqsmfh x where p.sckid=s.id and s.xmbm=sl.xmbm and sl.xmkid=x.id and x.unitcode like #{value}")
    List<HashMap> selectPLAN_AF(String str);

    @Select("select P.HTJE,P.WJSCZT,P.JGZT,P.JHXDWH,P.XFZT,P.NSQSJL,P.TZSJ,P.TZXZ,P.SJWGSJ,P.YJJGSJ,P.SJKGSJ,P.XDSJ,P.JHWGSJ1,P.JHKGSJ1,P.PFZTZ,P.PFSJ,P.PFWH,P.SJPFDW,P.SJDW,P.JHWGSJ,P.JHKGSJ,P.SBNF,P.SCKID,P.SGDW,P.SJSGTLJ,P.SJSGTMC,P.GKBGLJ,P.GKBGMC,P.SBSJ,P.SBBM,P.SBZT,P.SPSJ,P.JLDW,P.SPBM,P.SPZT,P.TBBM,P.TBSJ,P.ABLBZSQWH,P.SFSQABLBZ,P.JHSYDFZCJE,P.JHSYBZJE,P.ID,P.JAF,P.LS,P.SGXK,P.JHPC,P.SJJCQC,P.XIANJBZ,P.SHIJBZ,P.JHJSXZ,P.JHWGSJSTR,P.JHKGSJSTR,P.PLAN_WQGZ,P.ZLJDWJ,P.SHYJ1,P.SHYJ,P.SBBMDM,P.JH_SBTHCD,P.WJGYY,P.BZ,P.GYS,P.WJSJ,P.WJZT,P.XFBM,P.XFSJ,P.SHZT1,P.SHZT,P.SHIBZ,P.SHENGBZ,P.ZYJSNR,P.QLJSGM,P.QLSZXZ,P.SFKXG,P.SFYLRBWQK,P.JHQLQK,P.JHQLQC,P.ZDYF,P.SJSH,P.SJZT,P.XJZT,P.SFYLSJL,P.SPBMDM,P.XDZT,P.JSDW,P.KGZT,P.JGYSWJ,P.SGXKWJ,P.JGTCWJ from PLAN_wqgz p,sck_wqgz s,xmk_wqgz x where p.sckid=s.sckid and s.xmkid=x.id and x.gydwdm like #{value}")
    List<HashMap> selectPLAN_WQGZ(String str);

    @Select("select P.ID,P.LSSJ,P.SJSH,P.PLAN_ZHFZ,P.SJZT,P.XJZT,P.JHYHLC,P.JHZLC,P.JHZDZH,P.JHQDZH,P.ZDYF,P.SFYLSJL,P.SPBMDM,P.SBBMDM,P.JH_SBTHCD,P.GKBGMC,P.XDSJ,P.SBSJ,P.SBBM,P.SBZT,P.SPSJ,P.SPBM,P.SPZT,P.TBBM,P.SGXKWJ,P.HTJE,P.JLDW,P.SGDW,P.SJWGSJ,P.SJKGSJ,P.SJSGTLJ,P.SJSGTMC,P.GKBGLJ,P.WJGYY,P.BZ,P.GYS,P.WJSJ,P.WJZT,P.XFBM,P.XFSJ,P.XFZT,P.XDZT,P.JHXDWH,P.JSDW,P.YJWGSJ,P.JGZT,P.KGZT,P.WJSCZT,P.JGYSWJ,P.JGTCWJ,P.TBSJ,P.ABLBZSQWH,P.SFSQABLBZ,P.JHSYDFZCJE,P.JHSYBZJE,P.PFZTZ,P.PFSJ,P.PFWH,P.SBNF,P.JHKGSJ,P.JHWGSJ,P.SJPFDW,P.SJDW,P.SCKID from PLAN_zhfz p,sck_zhfz s,xmk_zhfz x where p.sckid=s.sckid and s.xmkid=x.id and x.gydwdm like #{value}")
    List<HashMap> selectPLAN_ZHFZ(String str);

    @Select("select SFQX,PLAN_ZJXD,DDZJLZ,TTC,GYDWDM,PARENT,JHXDWH,XMBM,YHDK,GZ,SZ,ZTZ,STC,DK,ZQ,ID,XMID,XDNF,XDZJ,SFZJ,TBDW,TBTIME,BTZZJ,STZ,QT,JL,RYS,DFZC,ZYJSNR,XZSCNL from PLAN_ZJXD")
    List<HashMap> selectPLAN_ZJXD(String str);

    @Select("select S.ID,S.CSYJ,S.CSZT,S.XZQH,S.XZQHDM,S.ABLBZSQWH,S.SFSQABLBZ,S.TBDWDM,S.SHZT,S.YHLC,S.STR5,S.STR4,S.STR3,S.STR2,S.STR1,S.JHNF,S.BZLS,S.XMBM,S.SHYJ,S.NSQBBZ,S.STR8,S.STR7,S.STR6,S.SBTHBMCD,S.XJGJND,S.LXMC,S.SBZT,S.ZDZH,S.QDZH,S.JSDJ,S.LXBM,S.BZ,S.JSNR,S.JSXZ,S.CZTZGS,S.CZZLC,S.SPWH,S.FASPSJ,S.FASCDW,S.FAPGDW,S.SCK_AQSMFH,S.TOWN,S.COUNTY,S.GYDWDM,S.GYDW,S.PROVINCE from sck_aqsmfh s,sck_aqsmfh_ld sl,xmk_aqsmfh x where  s.xmbm=sl.xmbm and sl.xmkid=x.id and x.unitcode like #{value}")
    List<HashMap> selectSCK_AQSMFH(String str);

    @Select("select SL.SCK_AQSMFH_LD,SL.STR8,SL.STR7,SL.STR6,SL.XMKID,SL.CZTZGS,SL.YHLC,SL.XJGJND,SL.LXMC,SL.ZDZH,SL.QDZH,SL.JSDJ,SL.LXBM,SL.STR5,SL.STR4,SL.STR3,SL.STR2,SL.STR1,SL.XMBM,SL.XUH,SL.XZQH,SL.XZQHDM,SL.PROVINCE,SL.TOWN,SL.COUNTY,SL.GYDWDM,SL.GYDW,SL.ID from sck_aqsmfh_ld sl,xmk_aqsmfh x where   sl.xmkid=x.id and x.unitcode like #{value}")
    List<HashMap> selectSCK_AQSMFH_LD(String str);

    @Select("select S.SCK_WQGZ,S.YDGLDJ,S.QLJC,S.SCTHDJ,S.CJQZ,S.RKSJ,S.SFYLRBWQK,S.SCK_SHYJ2,S.SCK_SHYJ1,S.SCK_SHZT1,S.JSKJZC,S.LS,S.SFJH,S.NSQSBZ,S.NSQSJL,S.SCAKJFL,S.ZDEZJ,S.SCSJHSPL,S.SFKXG,S.SCXSQ,S.SCSZXZ,S.SCSQS,S.SJSD,S.NSQBBZ,S.ZGQ,S.PFWH,S.SGTPFSJ,S.ZTZ,S.SCK_XBJGXS,S.KJZH,S.SCK_SBBM,S.SCK_SBSJ,S.SCK_SBZT,S.XMKID,S.SCBMBM,S.SCBZ,S.JSNR,S.JSXZ,S.FASPSJ,S.SCK_SBJGXS,S.HZDJ,S.JSGMQK,S.JSGMQC,S.SJDWMC,S.SCXMNF,S.SCQLQC,S.SCQLQK,S.BZLS,S.LRJH,S.SCK_SBTHCD,S.SCK_LXBM,S.SCK_QLZXZH,S.SCK_QLBH,S.SCK_SHBM,S.SCK_SHSJ,S.SCK_SHZT,S.SCKID,S.TZGS,S.SPWH,S.FASCDW,S.FAPGDW,S.REASON from sck_wqgz s,xmk_wqgz x where  s.xmkid=x.id and x.gydwdm like #{value}")
    List<HashMap> selectSCK_WQGZ(String str);

    @Select("select S.REASON,S.SCXMNF,S.BZLS,S.LRJH,S.SCK_SBTHCD,S.SCZLC,S.SCZDZH,S.SCQDZH,S.XMKID,S.SCBMBM,S.SCBZ,S.JSNR,S.JSXZ,S.FASPSJ,S.SCK_LXMC,S.SCK_LXBM,S.SCK_SHBM,S.SCK_SHSJ,S.SCK_SHZT,S.SCK_SBBM,S.SCK_SBSJ,S.SCK_SBZT,S.SCYHLC,S.SCKID,S.TZGS,S.SPWH,S.FASCDW,S.FAPGDW,S.SCK_ZHFZ from sck_zhfz s,xmk_zhfz x where  s.xmkid=x.id and x.gydwdm like #{value}")
    List<HashMap> selectSCK_ZHFZ(String str);

    @Select("select JDBS2,PK,XMLX,COLNAME,ID,TABLENAME,COLVALUE,JDBS,XH,LB from SJGX_TARGETS")
    List<HashMap> selectSJGX_TARGETS(String str);

    @Select("select SGPB,TSDQ,XJGJND,ZLC,SBTHCD,YHLC,GPSQD,GPSZD,TBBMBM,XUH,XMK_AQSMFH,DGJW,LXJW,JTLPBZB,DIST,DISTCODE,SBZT,CSZT,ZSZT,CSYJ,ZSYJ,ROADNAME,GLDJ,JCBZLS,LS,XMKLX,LSXMXX,LSJL,ID,PROVINCE,SJBL,LCXY,HJFZ,JCKBGF,JTL,XCHBC,CSXSSS,HUL,BZBX,PCSJ,LDFL,JTSGPCF,JTSGFXDJ,GLTJPCF,GLFXDJ,XBJYQX,LXXP,DOUP,TOWN,COUNTY,UNIT,UNITCODE,ROADCODE,JSDJ,FANGX,ROADSTART,ROADEND,JSHSXYD,AQSSQT,TJGC,HJZZ,BZBXCZ,JCKCZ,JZHL,JSHSXYDCZ,THROADSTART,THROADCODE,JHNF,AQSSQTCZ,TZGS,THROADEND from XMK_AQSMFH where unitcode like #{value}")
    List<HashMap> selectXMK_AQSMFH(String str);

    @Select("select SHYJ2,SBJGXS,BHNR,XZQHMC,BZ,TBBMBM,TBSJ,GYDWBM,GYDWDM,PTX,LSJL,ID,QLMC,QLBH,XZQHDM,LXMC,LXBM,GYDW,XJGJND,REASON,WQRKSJ,SQS,XSQ,BKQLBH,XLXBM,XQLBM,XZXZH,XLXMC,XMK_WQGZ,JCBZLS,XQLMC,XXCSJ,QQGZSJ,SFSC,SFWG,XMKLX,LSXMXX,JSDJ,PDDJ,QLZXZH,QLKD,QLQC,KJZC,DKZDKJ,AKJFL,PTY,XMNF,XMTYPE,SBZT,SBSJ,SHZT,SHSJ,ZQKS,QMJK,KYDWLX,THDJ,GLQLYT,QDLX,QTLX,PZLX,SFYAPJH,SBBM,SHBM,SBTHCD,TSDQ,SZXZ,SYNF,SJHSPL,QXJKUAN,QXJKONG,SHZT1,CZYJHJY,QLJGGCS,SFYLRBWQK,QLYHGCS,SHYJ1 from XMK_WQGZ where gydwdm like #{value}")
    List<HashMap> selectXMK_WQGZ(String str);

    @Select("select LSJL,LXMC,QDZH,ZDZH,QZLC,YHLC,GJXJND,YHNR,TBBMBM,TBSJ,YLXBM,YQDZH,YZDZH,YLXMC,XMK_ZHFZ,REASON,ID,GYDWDM,GYDWBM,GYDW,XZQHDM,XZQHMC,LXJSDJ,LXBM,XMNF,XMTYPE,SBZT,SBSJ,SBBM,SHZT,SHSJ,SHBM,XMKLX,TSDQ,ZLC,BZ,SBTHCD,LSXMXX from XMK_ZHFZ where gydwdm like #{value}")
    List<HashMap> selectXMK_ZHFZ(String str);

    @Select("select LSXMID,XMSQ_SH,ID,XMBM,GCFL,GHLXBH,YLXBH,XZQH,XZQHDM,QDZH,ZDZH,LC,LMKD,JSDJ,SQZT,XMMC,QDMC,ZDMC,LXMC,BZ,XZQHDM2,WNXMK,THYY,NTZ,JHKGSJ,JHWGSJ,GQ,TSDQ,GYDW,GYDWDM,JSFA,LSJL,WNXMID,WNNFXZ,WNXMBM,YHCSH,THYYYHC,LSXMBM from XMSQ_SH where gydwdm like #{value} ")
    List<HashMap> selectXMSQ_SH(String str);

    @Select("select JSDJ,NTZ,JHKGSJ,JHWGSJ,GQ,TSDQ,GYDW,GYDWDM,JSFA,LSJL,XMSQ_YHDZX,SQZT,XMMC,QDMC,ZDMC,LXMC,BZ,WNXMK,WNNFXZ,WNXMID,LSXMBM,LSXMID,ID,XMBM,GCFL,GHLXBH,YLXBH,JSXZ,YLMLX,YLMJG,XZQHDM2,XZQHMC2,THYY,YHCSH,THYYYHC,WNXMBM,LC,ZDZH,QDZH,XZQH,XZQHDM,LMKD from XMSQ_YHDZX where gydwdm like #{value}")
    List<HashMap> selectXMSQ_YHDZX(String str);

    @Select("select ZXLWZDZH,ZXLWQDZH,ID,ZXLWLXBM from ZGB_ZXLWZHTX_LXSH")
    List<HashMap> selectZGB_ZXLWZHTX_LXSH(String str);
}
